cray/generator.py, cray/modules/bos/cli.py, cray/modules/bos/openapi.yaml, cray/modules/bos/swagger3.json, tests/test_modules/test_bos.py
This adds the BOS v2 api to the cli.  It also adds a new way to inject code into the generator so that it's possible to access data at a point that is not otherwise possible.  This is necessary in order to setup a new bulk update endpoint for the cli.
* Resolves CASMCMS-7876
* Hela and others
We have been using this to call all the commands while testing BOS v2
None
=> CASMCMS-7876: Update BOS cli for v2

cray/modules/bos/cli.py, tests/test_modules/test_bos.py
Make BOS V2 the default for the CLI## Issues and Related PRs
_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._
* Resolves [issue id](issue link)
* Change will also be needed in `<insert branch name here>`
* Future work required by [issue id](issue link)
* Documentation changes required in [issue id](issue link)
* Merge with/before/after `<insert PR URL here>`
_List the environments in which these changes were tested._
* `gamora`
I updated the unit tests which passed.
I scp'ed a copy of the crayci RPM onto gamora. I invoked it as follows. This demonstrates that 'v2' is now the default version when none is specified.
ncn-m001:/mnt/developer/jasons/delete # ./usr/bin/cray bos sessions list
results = [] …
=> CASMCMS-8481: Make BOS V2 the default for the CLI

Jenkinsfile.github, pyproject.toml
- Fixes: CASMTRIAGE-5282
`botocore>=1.29.15` contains a change that breaks the `cray artifacts buckets list` command.
`boto3>=1.26` refers to the above, breaking change so it must also be downgraded.
Pin `boto3` and `botocore` to the last good version before the breaking change, until we can more or less fix it.
```bash
ncn-m002:~ # export CRAY_CREDENTIALS=/tmp/cmsdev-cray-credentials-file.810384.json
ncn-m002:~ # cray artifacts buckets list --format json
[
"admin-tools",
"badger",
"boot-images",
"config-data",
"etcd-backup",
"fw-update",
"ims",
"install-artifacts",
"nmd",
"postgres-backup",
"sat",
"sds",
"sls",
"sma",
"ssd",
"ssm",
"thanos",
"user",
"velero",
"wlm"
]
ncn-m002:~ # cray --version
cray, version 0.80.0.post2.dev1+g7c0872e
```
=> CASMTRIAGE-5282 Downgrade `botocore`

Jenkinsfile.github
Not sure if this change is necessary, but I noticed it when I was debugging the build failure.
=> Build using arti.hpc instead of arti.dev

cray/cli.py
- Fixes: CASMINST-6387
The `pyinstaller` build for `craycli` is producing an invalid binary that returns nothing (no flags or commands produce any output).
This block of code was removed in #100, and part of it needs to be returned.
This also cleans up the dual `CONTEXT_SETTING` and `CONTEXT_SETTINGS`.
RPM works:
```bash
8c3614bd6d2f:/mnt # rpm -Uvh craycli-0.81.2.dev1+ge402bd0-1.x86_64.rpm
Preparing...                          ################################# [100%]
Updating / installing...
1:craycli-0.81.2.dev1+ge402bd0-1   c################################# [100%]
8c3614bd6d2f:/mnt # cray
cray -hUsage: cray [OPTIONS] COMMAND [ARGS]...
Cray management and workflow tool
Options:
--version   Show the version and exit.
-h, --help  Show this message and exit.
Groups: …
```
=> CASMINST-6387 Fix `cray` Pyinstaller

cray/modules/ims/openapi.yaml, cray/modules/ims/swagger3.json, cray/tests/test_modules/test_ims.py
IMS will determine the correct filename if none is provided at CLI invoking with no --kernel-file-name based on the architecture.
- Fixes: https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8624
- Relates to: https://github.com/Cray-HPE/ims/pull/76
=> CASMCMS-8624: Removing defaults for ims `kernel_file_name`

cray/modules/bos/openapi.yaml, cray/modules/bos/swagger3.json, cray/tests/test_modules/test_bos.py
- Fixes: [CASMCMS-8674](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8674)
The `templateUrl` parameter has been broken in BOS since CSM 1.2. Since it has not been reported by anyone in that time, we're removing it from BOS. This PR removes it from the CLI as well.
I tested this on fanta along with the accompanying updated BOS. I ran the cmsdev bos test suite, and also tested creating and deleting v1 session templates.
Low risk -- the parameter already doesn't work.
=> CASMCMS-8674: Remove BOS templateUrl parameter

cray/modules/artifacts/cli.py
=> CASMTRIAGE-5555: remove unused argument

cray/modules/bos/openapi.yaml, cray/modules/bos/swagger3.json, cray/tests/test_modules/test_bos.py
- Fixes: https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8599
Adds --include-disabled CLI option, and adds a v2 session create test which includes it.
Testing underway currently. Will update shortly.
Low risk. Adding a single new flag to a single BOS CLI operation.
=> CASMCMS-8599: Add CLI support for `--include-disabled` option on v2 session creation

cray/cli.py
Change --tenant argument to be optional to prevent BW incompatible change for non-interactive use cases.
* https://jira-pro.it.hpe.com:8443/browse/CASMPET-6649
Tested on ashton:
```
ncn-m003:~/.config/cray/configurations # cray init --hostname https://api-gw-service-nmn.local
Overwrite configuration file at: /root/.config/cray/configurations/default ? [y/N]: y
Username: vshasta
Password:
Success!
Initialization complete.
ncn-m003:~/.config/cray/configurations # cat default
[core]
hostname = "https://api-gw-service-nmn.local"
tenant = ""
[auth.login]
username = "vshasta"
```
```
ncn-m003:~/.config/cray/configurations # cray init --hostname https://api-gw-service-nmn.local --tenant vcluster-blue
Overwrite configuration file at: /root/.config/cray/configurations/default ? [y/N]: y
Username: …
```
=> Remove required tenant prompt when initializing (CASMPET-6649)

cray/modules/artifacts/cli.py, pyproject.toml
Use boto3 pagination api to fully list bucket contents.
* https://jira-pro.it.hpe.com:8443/browse/CASMPET-6168
mug:
Before:
```
cray artifacts list thanos | grep ^Key | wc -l
1000
cray artifacts list velero | grep ^Key | wc -l
1000
```
After:
```
cray artifacts list thanos | grep ^Key | wc -l
1583
cray artifacts list velero | grep ^Key | wc -l
2913
```
Was a fresh Install tested? N
Was an Upgrade tested?      N - N/A
Was a Downgrade tested?     N - N/A
If schema changes were part of this change, how were those handled in your upgrade/downgrade testing? N/A
Low
* Nothing
=> Change cray artifacts to return more than 1000 files (CASMPET-6168)

cray/constants.py, cray/generator.py, cray/rest.py, cray/utils.py
Change how tenant name header is passed to also work with other headers.
* https://jira-pro.it.hpe.com:8443/browse/CASMINST-6514
mug:
```
ncn-w004:~/.config/cray/configurations # cray uas create --publickey ~/.ssh/id_rsa.pub --format toml -vvvv
Loaded token: /root/.config/cray/tokens/api_gw_service_nmn_local.vers
REQUEST: POST to https://api-gw-service-nmn.local/apis/uas-mgr/v1/uas
OPTIONS: {'params': {'imagename': None, 'ports': None}, 'data': <MultipartEncoder: {'publickey': ('id_rsa.pub', <_io.BufferedReader name='/root/.ssh/id_rsa.pub'>)}>, 'headers': {'Content-Type': 'multipart/form-data; boundary=183efc470a9645c4af49e8b12f917d14', 'Cray-Tenant-Name': 'vcluster-blue'}, 'verify': False}
uai_age = "0m"
uai_connect_string = "ssh vers@10.102.162.162"
uai_host = "ncn-w006"
uai_img = …
```
=> Add tenant name header allowing other headers (CASMINST-6514)

cray/modules/bos/cli.py, cray/tests/test_modules/test_bos.py
- Fixes: [CASMCMS-8905](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8905)
The ability to update a BOS v2 session is really intended for use only by the BOS service itself. Thus, it should not be in the CLI. This PR removes it.
I tested the updated CLI on mug and verified that the v2 sessions update option is gone, but the other options all remain.
=> CASMCMS-8905: Remove BOS v2 sessions update commands; add test to verify same

cray/modules/ims/openapi.yaml, cray/modules/ims/swagger3.json, cray/tests/test_modules/test_ims.py
CASMCMS-8795 - update the cray cli to include the new ims api to add/remove/list remote build nodes.
https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8795
I have tested this on Mug, Tyr, and Baldar. This interface was required for testing the new features on these systems.
If this version of the cray cli is installed on a system without the correct version of IMS that contains the new remote build nodes feature, that api will not work, but the rest of the api works exactly as it did before.
This is a low risk, as the other IMS api calls work independently from the new features.
=> CASMCMS-8795 - add remote build node api to IMS.

.gitignore, cray/modules/bos/cli.py, cray/tests/test_modules/test_bos.py
BOS v1 is finally going away in CSM 1.6.
It has already been removed from the cmsdev test tool and the barebones boot test.
This PR removes the BOS v1 command paths from the Cray CLI, along with the BOS v1 CLI tests.
It also adds some BOS v2 tests (although more should be added).
It does not replace the BOS swagger file because the CLI doesn't play nicely with `anyOf`/`allOf`/`oneOf`, which the current BOS API spec makes use of. Instead, I just modified the CLI generation for BOS to delete the `v1` paths.
I ran the CLI test suite and it passed (including all of the new/updated BOS tests). I also installed the RPM on mug and verified that the BOS CLI command still work, and that the v1 paths are missing.
- Fixes: [CASMCMS-8903](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8903)
- RFE …
=> CASMCMS-8903: Remove BOS v1 CLI commands & tests; add some BOS v2 tests

.gitignore, cray/modules/hsm/cli.py, cray/modules/hsm/swagger_v2.yaml
Added a workaround so that the global `--hostname` value (from the config file) does not get used in in `cray hsm redfishEndpoints update` and `cray hsm redfishEndpoints create`. These calls also have a `--hostname` option.
This PR also updates the hsm swagger file.
- Fixes: [CASMHMS-6154](https://jira-pro.it.hpe.com:8443/browse/CASMHMS-6154)
=> Added workaround for the conflict in --hostname

cray/modules/ims/openapi.yaml, cray/modules/ims/swagger3.json
- Requires: https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8833
Expands the definition of images to include user provided key value pairs of information as associated with an image.
Tested on `wasp`.
=> IMS: Add image tagging support

cray/modules/bos/openapi.yaml, cray/modules/bos/swagger3.json
CSM 1.5 PR for https://github.com/Cray-HPE/craycli/pull/155
See primary [BOS source PR](https://github.com/Cray-HPE/bos/pull/339) for more details.
All PRs:
BOS:
CSM 1.4: https://github.com/Cray-HPE/bos/pull/339
CSM 1.5: https://github.com/Cray-HPE/bos/pull/340
CSM 1.6: https://github.com/Cray-HPE/bos/pull/341
CLI:
CSM 1.4: https://github.com/Cray-HPE/craycli/pull/155
CSM 1.5: https://github.com/Cray-HPE/craycli/pull/156
CSM 1.6: https://github.com/Cray-HPE/craycli/pull/157
=> CASMTRIAGE-7147: Add BOS v2 max_component_batch_size option

cray/modules/bos/openapi.yaml, cray/modules/bos/swagger3.json
Update the BOS API spec to include the new `session_limit_required` option, so that it can be changes using the CLI.
I tested this on mug.
Backports:
* https://github.com/Cray-HPE/craycli/pull/159
* https://github.com/Cray-HPE/craycli/pull/160
BOS PRs:
* https://github.com/Cray-HPE/bos/pull/346
* https://github.com/Cray-HPE/bos/pull/347
* https://github.com/Cray-HPE/bos/pull/348
=> CASMCMS-9067: Add new BOS v2 session_limit_required option

cray/modules/ims/openapi.yaml, cray/modules/ims/swagger3.json, cray/tests/test_modules/test_ims.py
- Relates to: https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8979
Add command line api for new IMS remote build node status endpoints.
Installed the new craycli on Mug with the updated IMS service and verified all new commands work as expected. This will not impact any existing API's.
This is low risk as it is just introducing new apis to the IMS service.
=> CASMCMS-8979 - add status endpoint to cray ims remote-build-nodes.

cray/modules/bos/openapi.yaml, cray/modules/bos/swagger3.json
Updates the CLI for the new BOS `reject_nids` option.
Also updates the CLI to match the current BOS Session naming restrictions.
I tested this on fanta.
https://jira-pro.it.hpe.com:8443/browse/CASMCMS-7687
BOS source PR: https://github.com/Cray-HPE/bos/pull/367
=> CASMCMS-7687: Update CLI for new BOS reject_nids option

cray/modules/bos/openapi.yaml, cray/modules/bos/swagger3.json
(cherry picked from commit 7541dac36dabd971b1b7367e3a36b94ee1abffcc)
Add the cfs_read_timeout option.
- Fixes: CASMCMS-9162
- Requires:
- Relates to:
- [ x] I tested this on internal system (if yes, please include results or a description of the test)
I tested this on Drax, and I was able to update the cfs-read-timeout option.
=> CASMCMS-9162: Add the cfs_read_timeout option.

.github/workflows/promote-release.yml
Do not mark stable tags from release or maintenance branches as latest.
Prevents maintenance/release branches from declaring themselves as "latest" over a tag taken from the default branch.
=> Latest only on default branch

cray/modules/bos/openapi.yaml, cray/modules/bos/swagger3.json
Add support for new BOS options: `bss_read_timeout`, `hsm_read_timeout`, `ims_read_timeout`, and `pcs_read_timeout`.
I tested this on mug and verified that it works.
Backports forthcoming for CSM 1.5 and CSM 1.4
=> CASMCMS-9242: Update BOS OpenAPI spec to pull in new options

cray/modules/console/cli.py, cray/tests/test_modules/test_console.py, cray/tests/test_modules/test_ims.py, pyproject.toml
https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9033
This adds a cray cli interface for console services. It uses a websocket to interact with node consoles and to tail console log files. This allows us to restrict access to the consoles based on tenancy.
In order to restrict console access based on a users tenancy information, we needed to stop allowing/forcing users to interact with the console pods directly through K8S. Now there are endpoints in the console services that check tenancy authorization before allowing console interaction.
This is introducing a new module to the cray cli so should not impact existing functionality in any way.
=> CASMCMS-9090 - Create a module for console services.

cray/modules/bos/openapi.yaml, cray/modules/bos/swagger3.json
This updates the BOS API spec to the latest from the BOS repo, with the most notable change being the removal of the `disable_components_on_completion` option (associated with [this BOS PR](https://github.com/Cray-HPE/bos/pull/541))
=> CASMCMS-8131: BOS: Remove disable_components_on_completion option, update API spec
